---
title: "Examining the 'Early Access Effect' through bioRxiv preprints: summary analysis"
output: html_notebook
---

# Examining the 'Early Access Effect' through bioRxiv preprints: summary analysis

* Initial configuration
```{r}
# Call libraries
library(tidyverse)
```

```{r}
# Read files
distribution <- read.csv('data/bioRxiv_preprints_monthly_distribution.csv', header = TRUE)
published_articles <- read.csv('data/bioRxiv_preprints_published_articles_metadata.csv', header = TRUE)
control_articles <- read.csv('data/bioRxiv_control_articles_metadata.csv', header = TRUE)
```

```{r}
# Set figure variables
resolution <- 300 # DPI. R default is 72, 300 is high-resolution
x_ratio <- 16 # X-direction ratio for image size. We use 16:9 ratio
y_ratio <- 9 # Y-direction ratio for image size. We use 16:9 ratio
units <- "px" # Units
colour <- "black"
fill <- "#00bfff"
```

```{r}
# Distribution of preprints over time

# Monthly distribution of number of all preprints deposited to bioRxiv
png("outputs/bioRxiv_all_preprints_distribution.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(distribution, aes(x=date, y=preprints)) + 
  geom_bar(stat="identity", colour=colour, fill=fill) + 
  theme(text=element_text(size=24), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12))) +
  xlab("Date") +
  ylab("Deposited preprints")
dev.off()

# Monthly distribution of number of preprints deposited to bioRxiv that have links to published papers in Crossref
png("outputs/bioRxiv_published_preprints_distribution.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(distribution, aes(x=date, y=matching_preprints)) +
  geom_bar(stat="identity", colour=colour, fill=fill) +
  theme(text=element_text(size=24), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12))) +
  xlab("Date") +
  ylab("Published preprints")
dev.off()

# Monthly distribution of percentage of all preprints deposited to bioRxiv that have links to published papers in Crossref
png("outputs/bioRxiv_published_preprints_percentage.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(distribution, aes(x=date, y=(matching_preprints/preprints)*100)) +
  geom_bar(stat="identity", colour=colour, fill=fill) +
  theme(text=element_text(size=24), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12))) +
  xlab("Date") +
  ylab("Published preprints (% of deposited preprints)")
dev.off()

```
```{r}
# Distribution of time differences between deposition in bioRxiv and journal publication

time_diff = NULL

for (i in 1:length(published_articles$preprint_doi)){
  posted <- as.Date(published_articles$preprint_posted_date[i])
  created <- as.Date(published_articles$published_date[i])
  df <- data.frame("difference" = as.numeric(posted-created, "days"))
  time_diff <- rbind(time_diff, df)
}

png("outputs/bioRxiv_preprints_time_difference.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(time_diff, aes(difference)) +
  geom_histogram(colour=colour, fill=fill, breaks=seq(-1000, 200, by = 20)) +
  theme(text=element_text(size=24), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12))) +
  xlab("Time difference (days)") +
  ylab("Frequency")
dev.off()
```

```{r}
# Interaction of time difference with impact factor

df <- cbind(time_diff, "IF" = as.numeric(as.character((published_articles$IF))))

df$category <- ifelse(df$IF < 4, "low", ifelse(df$IF >=4 & df$IF < 8, "medium", ifelse(df$IF >= 8, "high",'NA')))
df$category_f <- factor(df$category, levels=c("high", "medium", "low"))
df$difference <- as.numeric(df$difference)
df <- df[complete.cases(df), ]

aggregate <- aggregate(df[, 1], list(df$category_f), mean)
mean_difference <- data.frame(category_f = c("low", "medium", "high"), mean = c(aggregate[3,2], aggregate[2,2], aggregate[1,2]))

png("outputs/bioRxiv_preprints_time_difference_IFs.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(df, aes(x=difference)) +
  facet_grid(rows = vars(category_f)) +
  geom_histogram(colour=colour, fill=fill, breaks=seq(-1000, 200, by = 20)) +
  theme(text=element_text(size=24), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12))) +
  xlab("Time difference (days)") +
  ylab("Frequency") + 
  geom_vline(aes(xintercept = mean), mean_difference, colour="black", linetype="dashed")
dev.off()

rm(time_diff, df, aggregate, mean_difference)
  
```

```{r}
# Journals
journals = published_articles$published_journal
journals = as.data.frame(table(journals))
journals <- journals[order(-journals$Freq),]
rownames(journals) <- 1:nrow(journals)
journals$journals <- factor(journals$journals, levels = journals$journals) #necessary to plot bars in descending order

#Plot top-30 most published in journals
png("outputs/bioRxiv_preprints_journal_distribution.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(journals[c(1:30),], aes(x=journals, y=Freq)) + 
  geom_bar(stat="identity", colour=colour, fill=fill) + 
  theme(text=element_text(size=24), axis.title.y = element_text(margin=margin(r=12)), axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("") +
  ylab("Frequency") +
  scale_x_discrete(labels = function(x) ifelse(nchar(x)>20, paste(strtrim(x, 17), "...", sep=""), x))
dev.off()
rm(journals)
```

```{r}
# Impact Factors
published_articles$IF <- as.numeric(as.character(published_articles$IF))
aggregate <- aggregate(published_articles$IF, list(cut(published_articles$IF, breaks=seq(0, 50, by=2))), FUN = length)

png("outputs/bioRxiv_preprints_IF_distribution.png", width = resolution*x_ratio, height = resolution*y_ratio, units = units, res=resolution)
ggplot(aggregate, aes(x=Group.1, y=x)) + 
  geom_bar(stat="identity", colour=colour, fill=fill) + 
  theme(text=element_text(size=24), axis.title.x = element_text(margin=margin(t=12)), axis.title.y = element_text(margin=margin(r=12)), axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Impact Factor") +
  ylab("Frequency")
dev.off()
rm(aggregate)
```

```{r}
# Article OA status

# OA status (OA or not OA)
published_is_oa = as.data.frame(table(published_articles$published_is_oa))
published_is_oa$Freq <- published_is_oa$Freq / sum(published_is_oa$Freq) * 100
control_is_oa = as.data.frame(table(control_articles$control_is_oa))
control_is_oa$Freq <- control_is_oa$Freq / sum(control_is_oa$Freq) * 100
published_is_oa$type <- "published"
control_is_oa$type <- "control"
is_oa <- rbind(published_is_oa, control_is_oa)
is_oa$type = factor(is_oa$type, levels=c('published', 'control'))
is_oa$Var1 = factor(is_oa$Var1, levels=c('TRUE', 'FALSE'))


png("outputs/bioRxiv_oa_summary.png", width = (resolution*x_ratio)/2, height = resolution*y_ratio, units = units, res=resolution)
ggplot(is_oa, aes(x=Var1, y=Freq)) + 
  geom_bar(stat="identity", colour=colour, fill=fill) +
  facet_grid(~type) +
  theme(text=element_text(size=24), axis.title.y = element_text(margin=margin(r=12)), axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("") +
  ylab("Frequency") +
  scale_x_discrete(labels = function(x) ifelse(nchar(x)>20, paste(strtrim(x, 17), "...", sep=""), x))
dev.off()

# OA host type
published_oa_host_type = as.data.frame(table(published_articles$published_oa_host_type))
published_oa_host_type$Freq <- published_oa_host_type$Freq / sum(published_oa_host_type$Freq) * 100
control_oa_host_type = as.data.frame(table(control_articles$control_oa_host_type))
control_oa_host_type$Freq <- control_oa_host_type$Freq / sum(control_oa_host_type$Freq) * 100
published_oa_host_type$type <- "published"
control_oa_host_type$type <- "control"
oa_host_type<- rbind(published_oa_host_type, control_oa_host_type)
oa_host_type$type = factor(oa_host_type$type, levels=c('published', 'control'))
oa_host_type$Var1 = factor(oa_host_type$Var1, levels=c('publisher', 'repository'))

png("outputs/bioRxiv_oa_host_type.png", width = (resolution*x_ratio)/2, height = resolution*y_ratio, units = units, res=resolution)
ggplot(oa_host_type, aes(x=Var1, y=Freq)) + 
  geom_bar(stat="identity", colour=colour, fill=fill) +
  facet_grid(~type) +
  theme(text=element_text(size=24), axis.title.y = element_text(margin=margin(r=12)), axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("") +
  ylab("Frequency") +
  scale_x_discrete(labels = function(x) ifelse(nchar(x)>20, paste(strtrim(x, 17), "...", sep=""), x))
dev.off()
rm(published_is_oa, control_is_oa, is_oa, published_oa_host_type, control_oa_host_type, oa_host_type)
```

```{r}
rm(published_articles, control_articles, distribution)
```


