CREATE TABLE BIORXIV_ALL_CONTROLS AS
SELECT DISTINCT
    T1.DOI AS ARTICLE_DOI, t1.ARTICLE_TITLE, T3.CREATED AS ARTICLE_CREATED_DATE,
    T1.PK_ITEMS, T1.UT_EID, T1.FK_SOURCES, t2.SOURCETITLE, T1.PAGE_CNT, T1.PUBTYPE, T1.DOCTYPE, T1.AUTHOR_CNT
FROM
    SCOPUS_B_2018.ITEMS t1
INNER JOIN
    SCOPUS_B_2018.SOURCES t2
ON
    t1.FK_SOURCES = t2.PK_SOURCES
    AND t2.SOURCETITLE IN (SELECT DISTINCT SOURCETITLE FROM BIORXIV_PUBLISHED_ARTICLES)
    AND t1.PUBTYPE = 'J'
    AND t1.DOCTYPE IN ('ar', 're')
    AND t1.PUBYEAR >= 2013
    AND t1.REF_CNT > 0
    AND lower(t1.DOI) NOT IN (SELECT ARTICLE_DOI FROM BIORXIV_PUBLISHED_ARTICLES)
    AND t1.PK_ITEMS NOT IN (SELECT PK_ITEMS FROM BIORXIV_PUBLISHED_ARTICLES)
INNER JOIN
    BIORXIV_CR_DATES t3
ON
    lower(t1.DOI) = t3.DOI

