SELECT DISTINCT
  t1.ARTICLE_DOI AS CITED_ARTICLE_DOI, t4.DOI AS CITING_ARTICLE_DOI, t5.CREATED AS CITING_ARTICLE_CREATED_DATE
FROM
  BIORXIV_ALL_ARTICLES t1
INNER JOIN
  SCOPUS_B_2018.ITEMS t2
ON
  t1.ARTICLE_DOI = LOWER(t2.DOI)
INNER JOIN
  SCOPUS_B_2018.CITINGITEMS t3
ON
  t2.PK_ITEMS = t3.FK_ITEMS_CITED
INNER JOIN
  SCOPUS_B_2018.ITEMS t4
ON
  t3.FK_ITEMS_CITING = t4.PK_ITEMS
INNER JOIN
  BIORXIV_CR_DATES t5
ON
  LOWER(t4.DOI) = t5.DOI