DELETE FROM 
  BIORXIV_ALL_CONTROLS 
WHERE
  LOWER(ARTICLE_TITLE) LIKE '%in this issue%'
  OR LOWER(ARTICLE_TITLE) LIKE '%corrigendum%'
  OR LOWER(ARTICLE_TITLE) LIKE '%erratum%'
  OR LOWER(ARTICLE_TITLE) LIKE '%table of contents%'
  OR LOWER(ARTICLE_TITLE) LIKE '%announcement%'
  OR LOWER(ARTICLE_TITLE) LIKE '%preface%'
  OR LOWER(ARTICLE_TITLE) LIKE '%books received%'
  OR LOWER(ARTICLE_TITLE) LIKE '%letter to the editor%'
  OR LOWER(ARTICLE_TITLE) LIKE '%introduction%'
  OR LOWER(ARTICLE_TITLE) LIKE '%reprint%'
  OR LOWER(ARTICLE_TITLE) LIKE '%correction%'
  OR LOWER(ARTICLE_TITLE) LIKE '%comment on%'
  OR LOWER(ARTICLE_TITLE) LIKE '%errata%'
  OR LOWER(ARTICLE_TITLE) LIKE '%retraction%'
  OR LOWER(ARTICLE_TITLE) LIKE '%reply to%'