SELECT
    t1.ARTICLE_DOI, t5.COUNTRYCODE, t5.INSTITUTION_FULL
FROM 
    BIORXIV_ALL_ARTICLES t1
INNER JOIN
  SCOPUS_B_2018.ITEMS t2
ON
  t1.ARTICLE_DOI = lower(t2.DOI)
INNER JOIN
  SCOPUS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t3
ON
  t2.PK_ITEMS = t3.FK_ITEMS
  AND t3.AUTHOR_POSITION = 1
INNER JOIN
  SCOPUS_B_2018.AUTHORS t4
ON
  t3.FK_AUTHORS = t4.PK_AUTHORS
INNER JOIN
  SCOPUS_B_2018.INSTITUTIONS t5
ON
  t3.FK_INSTITUTIONS = t5.PK_INSTITUTIONS




