SELECT DISTINCT
  t1.ARTICLE_DOI, COUNT(*) AS AUTHOR_PRODUCTIVITY
FROM 
  BIORXIV_FIRST_AUTHORS t1
INNER JOIN
  SCOPUS_B_2018.AUTHORS t2
ON
  t1.AUTHOR_ID = t2.AUTHOR_ID
INNER JOIN
  SCOPUS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t3
ON
  t2.PK_AUTHORS = t3.FK_AUTHORS
INNER JOIN
  SCOPUS_B_2018.ITEMS t4
ON
  t3.FK_ITEMS = t4.PK_ITEMS
  AND t4.PUBYEAR >= (t1.PUBYEAR-5)
GROUP BY ARTICLE_DOI