SELECT
    lower(SOURCETITLE) AS SOURCETITLE, CITYEAR AS YEAR, ROUND((SUM(CITING_DOCUMENTS)/SUM(CITED_DOCUMENTS)), 2) AS IF
FROM (
    SELECT
        t1.SOURCETITLE, t2.PUBYEAR AS PUBYEAR, t3.CITYEAR AS CITYEAR, COUNT(DISTINCT t3.FK_ITEMS_CITED) AS CITED_DOCUMENTS, COUNT(t3.FK_ITEMS_CITING) AS CITING_DOCUMENTS
    FROM
        SCOPUS_B_2018.SOURCES t1
    INNER JOIN
        SCOPUS_B_2018.ITEMS t2
    ON
        t1.PK_SOURCES = t2.FK_SOURCES
        AND lower(t1.SOURCETITLE) IN (SELECT SOURCETITLE FROM BIORXIV_ALL_ARTICLES)
        AND t2.PUBTYPE = 'J'
        AND t2.DOCTYPE IN ('ar', 're')
        AND t2.PUBYEAR >= 2011
        AND t2.PUBYEAR <= 2017
        AND t2.REF_CNT > 0
        AND t2.DOI IS NOT NULL
        -- Limit articles to journal articles, etcc
    INNER JOIN
        SCOPUS_B_2018.CITINGITEMS t3
    ON
        t3.FK_ITEMS_CITED = t2.PK_ITEMS
        AND (t3.CITYEAR = t2.PUBYEAR + 1 OR t3.CITYEAR = t2.PUBYEAR + 2)
    GROUP BY
        t1.SOURCETITLE, t2.PUBYEAR, t3.CITYEAR
    )
GROUP BY SOURCETITLE, CITYEAR)

