WITH PUBLISHED_ITEMS AS (SELECT
      SOURCETITLE, PUBYEAR, COUNT(DISTINCT FK_ITEMS) AS PUBLISHED_ITEMS
    FROM
      ITEMS_FOR_IF
    GROUP BY
      SOURCETITLE, PUBYEAR),
  CITING_ITEMS AS (SELECT
      SOURCETITLE, CITYEAR, COUNT(FK_ITEMS_CITING) AS CITING_ITEMS
    FROM
      ITEMS_FOR_IF t1
    INNER JOIN
      SCOPUS_B_2018.CITINGITEMS t2
    ON
      t2.FK_ITEMS_CITED = t1.FK_ITEMS
      AND (t2.CITYEAR = t1.PUBYEAR + 1 OR t2.CITYEAR = t1.PUBYEAR + 2)
    GROUP BY
      t1.SOURCETITLE, t2.CITYEAR)
SELECT
  t1.SOURCETITLE, t1.CITYEAR AS YEAR, ROUND(t1.CITING_ITEMS/SUM(t2.PUBLISHED_ITEMS), 2) AS IF
FROM
  CITING_ITEMS t1
INNER JOIN
  PUBLISHED_ITEMS t2
ON
  t1.SOURCETITLE = t2.SOURCETITLE
  AND (t1.CITYEAR = t2.PUBYEAR + 1 OR t1.CITYEAR = t2.PUBYEAR + 2)
  AND t1.CITYEAR <= 2017
GROUP BY t1.SOURCETITLE, t1.CITYEAR, t1.CITING_ITEMS;