SELECT DISTINCT
  t1.ARTICLE_DOI, (t1.PUBYEAR - MIN(t4.PUBYEAR) OVER (PARTITION BY t1.ARTICLE_DOI, t1.PUBYEAR)) AS AUTHOR_AGE
FROM 
  BIORXIV_LAST_AUTHORS t1
INNER JOIN
  SCOPUS_B_2018.AUTHORS t2
ON
  t1.AUTHOR_ID = t2.AUTHOR_ID
INNER JOIN
  SCOPUS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t3
ON
  t2.PK_AUTHORS = t3.FK_AUTHORS
INNER JOIN
  SCOPUS_B_2018.ITEMS t4
ON
  t3.FK_ITEMS = t4.PK_ITEMS