SELECT 
    PREPRINT_DOI, ARTICLE_DOI, ARTICLE_CREATED_DATE, ARTICLE_TITLE, FK_ITEMS, 
    UT_EID, FK_SOURCES, SOURCETITLE, PAGE_CNT, PUBTYPE, DOCTYPE, AUTHOR_CNT
FROM (
SELECT DISTINCT
    T1.PREPRINT_DOI, T3.*,
    ROW_NUMBER() OVER (PARTITION BY T1.PREPRINT_DOI ORDER BY DBMS_RANDOM.VALUE) AS ROWNUMBER
FROM
    BIORXIV_PUBLISHED_ARTICLES t1
INNER JOIN
    BIORXIV_PUBLISHED_MULTI_CITED t2
ON
    T1.FK_ITEMS = t2.FK_ITEMS
INNER JOIN
    BIORXIV_ALL_CONTROLS t3
ON
    t1.SOURCETITLE = t3.SOURCETITLE
    AND TO_CHAR(T3.ARTICLE_CREATED_DATE, 'YYYY-MM') = TO_CHAR(T1.ARTICLE_CREATED_DATE, 'YYYY-MM')
INNER JOIN
    BIORXIV_CONTROL_MULTI_CITED t4
ON
    t3.FK_ITEMS = t4.FK_ITEMS
    AND t2.CODE = t4.CODE)
WHERE
    ROWNUMBER <= 1
    ORDER BY PREPRINT_DOI