SELECT
    t1.REFTITLE, t1.SOURCETITLE, lower(t2.DOI) AS CITING_ARTICLE_DOI, t3.CREATED AS CITING_ARTICLE_CREATED_DATE
FROM
    SCOPUS_B_2018.REFERENCES t1
INNER JOIN
    SCOPUS_B_2018.ITEMS t2
ON
    lower(t1.SOURCETITLE) LIKE '%biorxiv%'
    AND t1.FK_ITEMS = t2.PK_ITEMS
INNER JOIN
    BIORXIV_CR_DATES t3
ON
    lower(t2.DOI) = t3.DOI