CREATE TABLE BIORXIV_PUBLISHED_ARTICLES AS
SELECT DISTINCT
    t2.PREPRINT_DOI, t2.ARTICLE_DOI, t4.CREATED AS ARTICLE_CREATED_DATE, t1.ARTICLE_TITLE, 
    t1.PK_ITEMS AS FK_ITEMS, t1.UT_EID, t1.FK_SOURCES, t3.SOURCETITLE, t1.PAGE_CNT, t1.PUBTYPE, t1.DOCTYPE, t1.AUTHOR_CNT
FROM
    SCOPUS_B_2018.ITEMS t1
INNER JOIN
    BIORXIV_PRE_PUB t2
ON
    lower(t1.DOI) = t2.ARTICLE_DOI
    AND t1.PUBTYPE = 'J'
    AND t1.DOCTYPE IN ('ar', 're')
    AND t1.PUBYEAR >= 2013
    AND t1.REF_CNT > 0
INNER JOIN
    SCOPUS_B_2018.SOURCES t3
ON
    t1.FK_SOURCES = t3.PK_SOURCES
INNER JOIN
    BIORXIV_CR_DATES t4
ON
    t2.ARTICLE_DOI = t4.DOI