CREATE TABLE BIORXIV_SCP_MATCHING_ITEMS AS
SELECT DISTINCT
    t4.PK_ITEMS AS PK_ITEMS,
    CONCAT(lower(regexp_substr(t2.LASTNAME, '^[^\. ]+')), lower(substr(t2.FIRSTNAME, 1, 1))) AS AUTHORNAME
FROM
    BIORXIV_PREPRINTS t1
INNER JOIN
    SCOPUS_B_2018.AUTHORS t2
ON
    CONCAT(lower(regexp_substr(t2.LASTNAME, '^[^\. ]+')), lower(substr(t2.FIRSTNAME, 1, 1))) = t1.PREPRINT_FIRST_AUTHOR
INNER JOIN
    SCOPUS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t3
ON
    t2.PK_AUTHORS = t3.fk_authors
    AND t3.AUTHOR_POSITION = '1'
INNER JOIN
    SCOPUS_B_2018.ITEMS t4
ON
    t3.FK_ITEMS = t4.PK_ITEMS
    AND t4.PUBYEAR >= t1.PREPRINT_POSTED_YEAR
    AND t4.AUTHOR_CNT = t1.PREPRINT_AUTHOR_COUNT
    AND t4.PUBTYPE = 'J'
    AND t4.DOCTYPE IN ('ar')
    AND t4.REF_CNT > 0
    AND t4.DOI IS NOT NULL
