SELECT
  t1.AUTHORNAME, t2.PK_ITEMS, t2.DOI, t2.ARTICLE_TITLE, t2.PUBYEAR, t2.AUTHOR_CNT, dbms_lob.substr(t3.TEXT, 100, 1) AS ABSTRACT_SHORT
FROM
  BIORXIV_FUZZY_MATCHING_ITEMS t1
INNER JOIN
  SCOPUS_B_2018.ITEMS t2
ON
  t1.PK_ITEMS = t2.PK_ITEMS
INNER JOIN
  SCOPUS_B_2018.ABSTRACTS t3
ON
  t1.PK_ITEMS = t3.FK_ITEMS
