SELECT
    DISTINCT PK_ITEMS, FK_SOURCES, FK_ISSUES, DOI, ARTICLE_TITLE, PAGE_CNT, PUBYEAR, PUBTYPE, DOCTYPE, AUTHOR_CNT, REF_CNT
FROM
    wos_b_2018.items t1
WHERE
    t1.FK_ISSUES in (SELECT FK_ISSUES FROM BIORXIV_SINGLE_CAT)
    AND t1.PUBTYPE = 'Journal'
    AND t1.DOCTYPE IN ('Article', 'Review')
    AND t1.REF_CNT > 0
    AND t1.DOI IS NOT NULL