SELECT
  CR_PREPRINT_DOI, CR_PUBLISHED_DOI, CR_PUBLISHED_TITLE, PK_ITEMS, FK_SOURCES, FK_ISSUES, DOI, ARTICLE_TITLE, PAGE_CNT, PUBYEAR, PUBTYPE, DOCTYPE, AUTHOR_CNT, REF_CNT
FROM
    BIORXIV_CR_PUBLISHED b
INNER JOIN
    wos_b_2018.items w
ON
    b.CR_PUBLISHED_DOI = LOWER(w.DOI) 
    AND w.PUBYEAR >= 2013 
    AND PUBTYPE = 'Journal' 
    AND DOCTYPE IN ('Article', 'Review')
    AND REF_CNT > 0
UNION
SELECT
    CR_PREPRINT_DOI, CR_PUBLISHED_DOI, CR_PUBLISHED_TITLE, PK_ITEMS, FK_SOURCES, FK_ISSUES, DOI, ARTICLE_TITLE, PAGE_CNT, PUBYEAR, PUBTYPE, DOCTYPE, AUTHOR_CNT, REF_CNT
FROM
    BIORXIV_CR_PUBLISHED b
INNER JOIN
    wos_b_2018.items w
ON
    b.CR_PUBLISHED_TITLE= LOWER(w.ARTICLE_TITLE) 
    AND w.PUBYEAR >= 2013 
    AND PUBTYPE = 'Journal' 
    AND DOCTYPE IN ('Article', 'Review')
    AND REF_CNT > 0