SELECT 
    PREPRINT_DOI, ARTICLE_DOI, ARTICLE_CREATED_DATE, ARTICLE_TITLE, FK_ITEMS, 
    UT_EID, FK_SOURCES, SOURCETITLE, PAGE_CNT, PUBTYPE, DOCTYPE, AUTHOR_CNT
FROM(
SELECT DISTINCT
    t1.PREPRINT_DOI, t3.*,
    ROW_NUMBER() OVER (PARTITION BY t1.PREPRINT_DOI ORDER BY DBMS_RANDOM.VALUE) AS ROWNUMBER
FROM
    BIORXIV_PUBLISHED_ARTICLES t1
INNER JOIN
    BIORXIV_PUBLISHED_SINGLE_CAT t2
ON
    t1.ARTICLE_DOI = t2.ARTICLE_DOI
INNER JOIN
    BIORXIV_ALL_CONTROLS t3
ON
    t1.SOURCETITLE = t3.SOURCETITLE
    AND TO_CHAR(t3.ARTICLE_CREATED_DATE, 'YYYY-MM') = TO_CHAR(T1.ARTICLE_CREATED_DATE, 'YYYY-MM'))
WHERE
    ROWNUMBER <= 1
    ORDER BY PREPRINT_DOI